[tool.poetry]
name = "bfv-hacker-checker"
version = "0.1.0"
description = ""
authors = ["Albrecht Nitsche <albrechtnitsche@mail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pyinstaller = "^5.9.0"
poethepoet = "^0.19.0"
pillow = "^9.4.0"
pyqt5 = "^5.15.9"
pyqt5-sip = "^12.11.1"
pyqtwebengine = "^5.15.6"
pynput = "^1.7.6"
pywin32 = "^306"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
app = "python main.py"
build = "build.bat"


